### ISSUE TITLE
Noticed a few missing letters in some of the currency names

### ISSUE THREAD

**Issue by cs-NET** [xsolla/angular-currency-format#1]
Currency XUA: "ADB Unit of ccount" should be "ADB Unit of Account"

Currency TTD: "Trinidad nd Tobago Dollar" should be "Trinidad and Tobago Dollar"

Maybe the parser is stripping out whitespace+A??

**Comment by apigraf** [comment]
It's a misprint.
Fixed in 3dc69c698ed1e892d823dd4281dc0dcc66bbac33.
Thank you.
